module FinModeling
  class AssetsItem < String
    TRAINING_VECTORS = [ {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Assets Held For Sale Current"},
                         {:klass=>:oa, :item_string=>"Funds Held Clients"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
  
                         {:klass=>:oa, :item_string=>"Content Library Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Content Library Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Content Library Net Noncurrent"},

                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense Current"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:oa, :item_string=>"Assets Of Disposal Group Including Discontinued Operation Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Deferred Income Taxes And Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
  
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Equity Method Investments"},
                         {:klass=>:oa, :item_string=>"Nontrade Receivables Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Deferred Costs Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:fa, :item_string=>"Income Taxes Receivable"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Other Receivables Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Deferred Costs Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Acquired Finite Lived Intangible Asset Amount"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Notes And Loans Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Capitalized Computer Software Net"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Notes And Loans Receivable Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expenses And Other Current Assets"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Restricted Cash"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Equity Method Investments"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Noncurrent"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Gross"},
                         {:klass=>:oa, :item_string=>"Accumulated Depreciation Depletion And Amortization Property Plant And Equipment"},
                         {:klass=>:fa, :item_string=>"Deposits And Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Long Term Accounts Notes And Loans Receivable Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Receivables Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Hedging Assets Current"},
                         {:klass=>:fa, :item_string=>"Hedging Assets Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Held To Maturity Securities Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Receivables Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Capitalized Computer Software Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Held To Maturity Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Finance Costs Noncurrent Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Deferred Costs And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:oa, :item_string=>"Deferred Costs And Other Assets"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
  
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Gross Noncurrent"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Income Taxes Receivable"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Income Taxes Receivable"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Notes And Loans Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Notes And Loans Receivable Net Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Costs In Excess Of Billings On Uncompleted Contracts Or Programs Expected To Be Collected Within One Year"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment And Capitalized Software Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Notes And Loans Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Notes And Loans Receivable Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Debt Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Equity Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts And Other Receivables Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Restricted Investments Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Cash Equivalents"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Customer Related Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Other Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Unbilled Contracts Receivable"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Inventory For Long Term Contracts Or Programs"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Project Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:fa, :item_string=>"Marketable Securities Noncurrent"},
                         {:klass=>:fa, :item_string=>"Restricted Cash And Investments Noncurrent"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Inventory Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Receivable Under Reverse Repurchase Agreements"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Revenue Share Expenses And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Revenue Share Expenses And Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:fa, :item_string=>"Other Long Term Investments"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Income Taxes Receivable"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:fa, :item_string=>"Income Tax Receivable"},
                         {:klass=>:oa, :item_string=>"Prepayments And Other Current Assets"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:fa, :item_string=>"Investments In Affiliates Subsidiaries Associates And Joint Ventures"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Deposits And Other Assets Noncurrent"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Liabilities Net"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Gross Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Debt Securities Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Income Taxes Receivable"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Funds Held For Clients"},
                         {:klass=>:fa, :item_string=>"Available For Sale Securities Debt Securities Noncurrent"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Inventory Net"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:fa, :item_string=>"Short Term Investments"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense And Other Assets Current"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:fa, :item_string=>"Long Term Investments"},
                         {:klass=>:oa, :item_string=>"Tradenames Net"},
                         {:klass=>:oa, :item_string=>"Patent And Patent Licenses Net"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Net"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Intangible Assets Net Excluding OA Goodwill"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Noncurrent"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"},
                         {:klass=>:oa, :item_string=>"Customer Relationships Net"},
  
                         {:klass=>:fa, :item_string=>"Cash And Cash Equivalents At Carrying Value"},
                         {:klass=>:oa, :item_string=>"Accounts Receivable Net Current"},
                         {:klass=>:oa, :item_string=>"Prepaid Expense Current"},
                         {:klass=>:oa, :item_string=>"Other Assets Current"},
                         {:klass=>:fa, :item_string=>"Deferred Tax Assets Net Current"},
                         {:klass=>:oa, :item_string=>"Property Plant And Equipment Gross"},
                         {:klass=>:oa, :item_string=>"Accumulated Depreciation Depletion And Amortization Property Plant And Equipment"},
                         {:klass=>:oa, :item_string=>"Goodwill"},
                         {:klass=>:oa, :item_string=>"Finite Lived Intangible Assets Net"},
                         {:klass=>:fa, :item_string=>"Deferred Finance Costs Noncurrent Net"},
                         {:klass=>:oa, :item_string=>"Other Assets Noncurrent"} ]
  
  end
end
