module FinModeling
  class IncomeStatementItem < String
    TRAINING_VECTORS = [ {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance Revenue"}, 
                         {:klass=>:or, :item_string=>"Technology Services Revenue"}, 
                         {:klass=>:or, :item_string=>"Other Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation And Amortization"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 

                         {:klass=>:cogs, :item_string=>"Fulfillment Expense"},
                         {:klass=>:cogs, :item_string=>"Fulfillment Expense"},
                         {:klass=>:cogs, :item_string=>"Fulfillment Expense"},
  
                         {:klass=>:or, :item_string=>"Net Sales"}, 
                         {:klass=>:cogs, :item_string=>"Cost of products sold"}, 
                         {:klass=>:oe, :item_string=>"Marketing, selling and administrative"}, 
                         {:klass=>:oe, :item_string=>"Advertising and product promotion"}, 
                         {:klass=>:oe, :item_string=>"Research and development"}, 
                         {:klass=>:oibt, :item_string=>"Provision for restructuring"}, 
                         {:klass=>:oibt, :item_string=>"Litigation expense, net"}, 
                         {:klass=>:oibt, :item_string=>"Equity in net income of affiliates"}, 
                         {:klass=>:oibt, :item_string=>"Other (income)/expense"}, 
                         {:klass=>:tax, :item_string=>"Provision for income taxes"}, 

                         {:klass=>:or, :item_string=>"Subscription Revenue"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Subscription"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Marketing And Advertising Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Acquired Intangible Assets"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Goodwill And Intangible Asset Impairment"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Settlement And Impairment Provisions"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat_nci, :item_string=>"Net Income Loss Attributable To Noncontrolling Interest"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:or, :item_string=>"Subscription Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Subscription"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Software Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:oibt, :item_string=>"Amortization Of Intangible Asets And Incomplete Technology"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Investments"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance Revenue"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Maintenance Costs"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income Expense Net"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Recurring"}, 
                         {:klass=>:or, :item_string=>"Non Recurring"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Recurring"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Non Recurring"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Developed Technology"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:oibt, :item_string=>"Gain Loss On Sale Of Equity Investments"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat, :item_string=>"Income Loss From Discontinued Operations Net Of Tax Attributable To Reporting Entity"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Compensation Expense Benefit Deferred Compensation Plan"}, 
                         {:klass=>:oe, :item_string=>"Loss Gain On Deferred Compensation Plan Securities"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance And Service Revenue"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Amortization"}, 
                         {:klass=>:cogs, :item_string=>"Maintenance And Service Costs"}, 
                         {:klass=>:cogs, :item_string=>"Severance Costs Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oe, :item_string=>"Severance Costs"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Business Combination Integration Related Costs"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"License And Maintenance Revenue"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services Licenses And Maintenance Agreements"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services Amortization"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat, :item_string=>"Income Loss From Discontinued Operations Net Of Tax"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Business Combination Acquisition Related Costs"}, 
                         {:klass=>:oe, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oe, :item_string=>"Goodwill And Intangible Asset Impairment"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Investments"}, 
                         {:klass=>:fibt, :item_string=>"Foreign Currency Transaction Gain Loss Before Tax"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Gains Losses On Extinguishment Of Debt"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Ratable Product And Related Professional Services And Support Revenue"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Technology Services Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Technology Services Costs"}, 
                         {:klass=>:cogs, :item_string=>"Ratable Product And Related Professional Services And Support Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Business Combination Acquisition Related Costs"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Disposition Of Assets"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Technology Services Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance Revenue"}, 
                         {:klass=>:or, :item_string=>"Subscription Revenue"}, 
                         {:klass=>:or, :item_string=>"Other Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:cogs, :item_string=>"Maintenance Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Subscription"}, 
                         {:klass=>:cogs, :item_string=>"Other Cost Of Operating Revenue"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Other Cost And Expense Operating"}, 
                         {:klass=>:oibt, :item_string=>"Other Operating Income Expense"},
                         {:klass=>:fibt, :item_string=>"Costmethod Investments Other Than Temporary Impairment"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat, :item_string=>"Income Loss From Equity Method Investments"},
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance Revenue"}, 
                         {:klass=>:or, :item_string=>"Technology Services Revenue"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Maintenance Costs"}, 
                         {:klass=>:cogs, :item_string=>"Technology Services Costs"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Software Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income And Other"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Investments"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Legal Fees"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Sale Of Other Assets"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Disposition Of Assets"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest And Dividend"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Goodwill Impairment Loss"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Sale Of Business"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat_nci, :item_string=>"Net Income Loss Attributable To Noncontrolling Interest"}, 
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance Revenue"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services Maintenance Costs"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Revenues"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation Depletion And Amortization"}, 
                         {:klass=>:fibt, :item_string=>"Gains Losses On Extinguishment Of Debt"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Net"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:or, :item_string=>"Reimbursement Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Sales And Client Services Expense"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Reimbursable Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Software Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income Expense Nonoperating Net"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Subscription"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Revaluation Of Contingent Consideration"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:oibt, :item_string=>"Income Loss From Equity Method Investments"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat_nci, :item_string=>"Net Income Loss Attributable To Noncontrolling Interest"}, 
  
                         {:klass=>:or, :item_string=>"Revenues"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Gain Loss On Disposition Of Property"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Acquisition Costs"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income Expense Net"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Costs Including Software Development Costs"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring And Other Charges"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest And Dividend"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest And Other Income"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue Excluding Depreciation And Amortization"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation And Amortization"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest And Dividend"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Revenue From Related Parties"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Foreign Currency Transaction Gain Loss Before Tax"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Impairment Of Investments"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat_nci, :item_string=>"Net Income Loss Attributable To Noncontrolling Interest"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Excluding Acquired In Process Cost"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Amortization"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Information Technology And Data Processing"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation And Amortization"}, 
                         {:klass=>:oe, :item_string=>"Finite Lived Intangible Assets Amortization Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Software Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:fibt, :item_string=>"Change In Fair Value Of Acquisition Related Contingent Consideration"}, 
                         {:klass=>:oibt, :item_string=>"Goodwill Impairment Loss"}, 
                         {:klass=>:oibt, :item_string=>"Merger And Acquisition Costs"}, 
                         {:klass=>:oibt, :item_string=>"Research And Development In Process"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring And Other Charges"}, 
                         {:klass=>:fibt, :item_string=>"Realized Gains Losses On Strategic Investments"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation And Amortization"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring And Acquisition Related Costs"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense Income Net Including Other Miscellaneous Items"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Subscriptions And Transactions"}, 
                         {:klass=>:or, :item_string=>"Service And Maintenance"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Software Licenses"}, 
                         {:klass=>:or, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Sales Subscriptions And Transactions"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenues Service And Maintenance"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Technology Services Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:oe, :item_string=>"Technology Services Costs"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Software Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation Nonproduction"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Net"}, 
                         {:klass=>:oibt, :item_string=>"Business Combination Contingent Consideration Arrangements Change In Amount Of Contingent Consideration Liability"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Production Start Up Expense"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:oibt, :item_string=>"Goodwill Impairment Loss"}, 
                         {:klass=>:fibt, :item_string=>"Foreign Currency Transaction Gain Loss Before Tax"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Charge Related To Resolution Of Investigation"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Goods Net"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Finite Lived Intangible Assets Amortization Expense Operating Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation Depletion And Amortization"}, 
                         {:klass=>:fibt, :item_string=>"Interest And Other Income"}, 
                         {:klass=>:fibt, :item_string=>"Interest And Other Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development In Process"}, 
                         {:klass=>:oe, :item_string=>"Goodwill And Acquisition Related Intangible Assets Impairment"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Disposition Of Assets"}, 
                         {:klass=>:oibt, :item_string=>"Equity Method Investment Other Than Temporary Impairment"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income And Other Expense Net"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Data Center Services Revenue"}, 
                         {:klass=>:or, :item_string=>"Internet Protocol Services And Products Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Data Center Services Cost"}, 
                         {:klass=>:cogs, :item_string=>"Internet Protocol Services And Products Cost"}, 
                         {:klass=>:cogs, :item_string=>"Direct Cost Of Customer Support"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Acquired Intangible Assets"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation And Amortization"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Sale Of Property Plant Equipment"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Settlement And Impairment Provisions"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat, :item_string=>"Income Loss From Equity Method Investments Net Of Tax"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Foreign Currency Transaction Gain Loss Before Tax"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:ooiat_nci, :item_string=>"Net Income Loss Attributable To Noncontrolling Interest"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Amortization"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Disposal Of Assets And Impairment Of Long Lived Assets"}, 
                         {:klass=>:oibt, :item_string=>"Business Exit Costs"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Impairment Of Investments"}, 
                         {:klass=>:fibt, :item_string=>"Gain On Sale Of Investments"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Advertising Revenue"}, 
                         {:klass=>:cogs, :item_string=>"Advertising Revenue Cost"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Other General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation Amortization And Accretion Net"}, 
                         {:klass=>:fibt, :item_string=>"Gain Loss On Disposition Of Assets"}, 
                         {:klass=>:fibt, :item_string=>"Gains Losses On Extinguishment Of Debt"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
                         {:klass=>:fiat, :item_string=>"Dividends Preferred Stock"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Gains Losses On Extinguishment Of Debt"}, 
                         {:klass=>:fibt, :item_string=>"Interest And Other Income"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income Expense Net"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Revenues"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Operating Expenses Restructurings And Asset Impairment Charges"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Foreign Currency Transaction Gain Loss Before Tax"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Sales Revenue Services Net"}, 
                         {:klass=>:or, :item_string=>"Hardware Revenue And Other"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Hardware And Other"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Depreciation Depletion And Amortization"}, 
                         {:klass=>:fibt, :item_string=>"Recovery Of Previously Impaired Investment"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Income Expense Net"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Licenses Revenue"}, 
                         {:klass=>:or, :item_string=>"Maintenance Revenue"}, 
                         {:klass=>:cogs, :item_string=>"License Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Services Maintenance Costs"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods Sold Amortization"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Software Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:oibt, :item_string=>"Income Loss From Equity Method Investments"}, 
                         {:klass=>:oibt, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Other Restructuring Costs"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Impairment And Restructuring Expenses"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Revenue"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense"}, 
                         {:klass=>:oe, :item_string=>"Selling And Marketing Expense"}, 
                         {:klass=>:oe, :item_string=>"General And Administrative Expense"}, 
                         {:klass=>:fibt, :item_string=>"Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"}, 
  
                         {:klass=>:or, :item_string=>"Sales Revenue Net"}, 
                         {:klass=>:cogs, :item_string=>"Cost Of Goods And Services Sold"}, 
                         {:klass=>:oe, :item_string=>"Selling General And Administrative Expense"}, 
                         {:klass=>:oe, :item_string=>"Research And Development Expense Excluding Acquired In Process Cost"}, 
                         {:klass=>:oe, :item_string=>"Amortization Of Intangible Assets"}, 
                         {:klass=>:oibt, :item_string=>"Restructuring Charges"}, 
                         {:klass=>:fibt, :item_string=>"Interest Expense"}, 
                         {:klass=>:fibt, :item_string=>"Investment Income Interest"}, 
                         {:klass=>:fibt, :item_string=>"Other Nonoperating Income Expense"}, 
                         {:klass=>:tax, :item_string=>"Income Tax Expense Benefit"} ]
  end
end
