module FinModeling
  class CashChangeItem < String
    TRAINING_VECTORS = [ { :klass=>:c, :item_string=>"Net Income Loss" },
                         { :klass=>:c, :item_string=>"Depreciation" },
                         { :klass=>:c, :item_string=>"Adjustment For Amortization" },
                         { :klass=>:c, :item_string=>"Deferred Income Tax Expense Benefit" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Excess Tax Benefit From Share Based Compensation Operating Activities" },
                         { :klass=>:c, :item_string=>"Other Noncash Income Expense" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Current Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Noncurrent Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Employee Related Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Income Taxes Payable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Liabilities" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Software" },
                         { :klass=>:i, :item_string=>"Alliance Technical Enablement Expenditures" },
                         { :klass=>:d, :item_string=>"Payments To Acquire Available For Sale Securities" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Other Productive Assets" },
                         { :klass=>:f, :item_string=>"Proceeds From Issuance Of Common Stock" },
                         { :klass=>:f, :item_string=>"Proceeds From Stock Options Exercised" },
                         { :klass=>:f, :item_string=>"Excess Tax Benefit From Share Based Compensation Financing Activities" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Other Equity" },
                         { :klass=>:d, :item_string=>"Repayments Of Lines Of Credit" },
                         { :klass=>:d, :item_string=>"Proceeds From Lines Of Credit" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt And Capital Securities" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents" },

                         { :klass=>:c, :item_string=>"Amortization Of Content Databases" },
                         { :klass=>:c, :item_string=>"Net Income Loss" },
                         { :klass=>:c, :item_string=>"Depreciation" },
                         { :klass=>:c, :item_string=>"Amortization Of Intangible Assets" },
                         { :klass=>:c, :item_string=>"Amortization Of Financing Costs" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Income Taxes Net" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Restricted Cash For Operating Activities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Income Taxes Payable Net Of Income Taxes Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable And Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Excess Tax Benefit From Share Based Compensation Operating Activities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Content Data Base Costs" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:d, :item_string=>"Payments To Acquire Available For Sale Securities" },
                         { :klass=>:f, :item_string=>"Proceeds From Stock Options Exercised" },
                         { :klass=>:f, :item_string=>"Proceeds From Issuance Initial Public Offering" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt" },
                         { :klass=>:f, :item_string=>"Excess Tax Benefit From Share Based Compensation Financing Activities" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents" },

                         { :klass=>:c, :item_string=>"Profit Loss" },
                         { :klass=>:c, :item_string=>"Goodwill And Intangible Asset Impairment" },
                         { :klass=>:c, :item_string=>"Depreciation Amortization And Impairment Of Long Lived Assets" },
                         { :klass=>:c, :item_string=>"Gain Loss On Disposition Of Assets" },
                         { :klass=>:c, :item_string=>"Deferred Income Tax Expense Benefit" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Charges" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable And Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:i, :item_string=>"Payments For Proceeds From Businesses And Interest In Affiliates" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments To Develop Capitalized Software" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments For Proceeds From Investments" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Other Productive Assets" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Businesses Net Of Cash Acquired" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Intangible Assets" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt" },
                         { :klass=>:d, :item_string=>"Payments Of Debt Restructuring Costs" },
                         { :klass=>:d, :item_string=>"Payments Of Dividends" },
                         { :klass=>:f, :item_string=>"Proceeds From Issuance Of Common Stock" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:d, :item_string=>"Proceeds From Minority Shareholders" },
                         { :klass=>:f, :item_string=>"Excess Tax Benefit From Share Based Compensation Financing Activities" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents" },

                         { :klass=>:c, :item_string=>"Net Income Loss" },
                         { :klass=>:c, :item_string=>"Depreciation Depletion And Amortization" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Deferred Income Taxes And Tax Credits" },
                         { :klass=>:c, :item_string=>"Unrealized Gain Loss On Investments" },
                         { :klass=>:c, :item_string=>"Tax Benefit From Stock Options Exercised" },
                         { :klass=>:c, :item_string=>"Excess Tax Benefit From Share Based Compensation Operating Activities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Receivables" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Prepaid Deferred Expense And Other Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Restructuring Reserve" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Income Taxes Payable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:c, :item_string=>"Other Noncash Income Expense" },
                         { :klass=>:i, :item_string=>"Gain Loss On Sale Of Property Plant Equipment" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Longterm Investments" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Short Term Investments" },
                         { :klass=>:d, :item_string=>"Proceeds From Maturities Prepayments And Calls Of Shortterm Investments" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Short Term Investments" },
                         { :klass=>:d, :item_string=>"Proceeds From Sale Of Available For Sale Securities Equity" },
                         { :klass=>:i, :item_string=>"Payments For Proceeds From Other Investing Activities" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Businesses Net Of Cash Acquired" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:d, :item_string=>"Payments Of Debt Issuance Costs" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:f, :item_string=>"Proceeds From Sale Of Treasury Stock" },
                         { :klass=>:f, :item_string=>"Excess Tax Benefit From Share Based Compensation Financing Activities" },
                         { :klass=>:d, :item_string=>"Proceeds From Issuance Of Senior Long Term Debt" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt And Capital Securities" },
                         { :klass=>:d, :item_string=>"Repayments Of Acquired Debt" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents" },

                         { :klass=>:c, :item_string=>"Net Income Loss" },
                         { :klass=>:c, :item_string=>"Research And Development In Process" },
                         { :klass=>:c, :item_string=>"Depreciation And Amortization" },
                         { :klass=>:c, :item_string=>"Asset Impairment Charges" },
                         { :klass=>:c, :item_string=>"Restructuring Costs" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Income Taxes" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Prepaid Deferred Expense And Other Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable And Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Income Taxes Payable" },
                         { :klass=>:d, :item_string=>"Payments To Acquire Marketable Securities" },
                         { :klass=>:d, :item_string=>"Proceeds From Sale Of Available For Sale Securities" },
                         { :klass=>:d, :item_string=>"Proceeds From Maturities Prepayments And Calls Of Available For Sale Securities" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Businesses Net Of Cash Acquired" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Investments" },
                         { :klass=>:f, :item_string=>"Proceeds From Issuance Of Common Stock" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:d, :item_string=>"Proceeds From Lines Of Credit" },
                         { :klass=>:d, :item_string=>"Repayments Of Lines Of Credit" },

                         { :klass=>:c, :item_string=>"Income Loss From Continuing Operations" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Depreciation Depletion And Amortization" },
                         { :klass=>:c, :item_string=>"Excess Tax Benefit From Share Based Compensation Operating Activities" },
                         { :klass=>:c, :item_string=>"Provision For Doubtful Accounts" },
                         { :klass=>:c, :item_string=>"Sales Allowances Services" },
                         { :klass=>:c, :item_string=>"Gain Loss On Sale Of Property Plant Equipment" },
                         { :klass=>:c, :item_string=>"Asset Impairment Charges" },
                         { :klass=>:c, :item_string=>"Gain Loss On Investments" },
                         { :klass=>:c, :item_string=>"Deferred Income Tax Expense Benefit" },
                         { :klass=>:c, :item_string=>"Other Noncash Income Expense" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Prepaid Deferred Expense And Other Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Income Taxes Payable" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Businesses Net Of Cash Acquired" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments For Capitalized Software Development Costs" },
                         { :klass=>:d, :item_string=>"Proceeds From Sale Maturity And Collections Of Investments" },
                         { :klass=>:d, :item_string=>"Payments To Acquire Marketable Securities" },
                         { :klass=>:d, :item_string=>"Proceeds From Sale And Maturity Of Marketable Securities" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Productive Assets" },
                         { :klass=>:d, :item_string=>"Increase Decrease In Restricted Cash" },
                         { :klass=>:f, :item_string=>"Proceeds From Stock Options Exercised" },
                         { :klass=>:f, :item_string=>"Payments Of Withholding Taxes Equity Award Share Settlement Net" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:f, :item_string=>"Proceeds From Stock Plans" },
                         { :klass=>:d, :item_string=>"Proceeds From Issuance Of Long Term Debt" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt" },
                         { :klass=>:d, :item_string=>"Payments Of Debt Issuance Costs" },
                         { :klass=>:f, :item_string=>"Excess Tax Benefit From Share Based Compensation Financing Activities" },
                         { :klass=>:d, :item_string=>"Net Cash Transferred To From Discontinued Operations" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents Continuing Operations" },

                         { :klass=>:c, :item_string=>"Profit Loss" },
                         { :klass=>:c, :item_string=>"Depreciation Depletion And Amortization" },
                         { :klass=>:c, :item_string=>"Amortization Of Financing Costs And Discounts" },
                         { :klass=>:c, :item_string=>"Provision For Doubtful Accounts" },
                         { :klass=>:c, :item_string=>"Deferred Income Tax Expense Benefit" },
                         { :klass=>:c, :item_string=>"Income Loss From Equity Method Investments" },
                         { :klass=>:c, :item_string=>"Gains Losses On Extinguishment Of Debt Attributable To Financing Activities" },
                         { :klass=>:c, :item_string=>"Gain Loss On Sale Of Property Plant Equipment" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Other Noncash Income Expense" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Receivables" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Inventories" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Liabilities" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Proceeds From Sale Of Property Plant And Equipment" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Equity Method Investments" },
                         { :klass=>:i, :item_string=>"Purchase Of Equipment Leased To Unconsolidated Affiliate" },
                         { :klass=>:i, :item_string=>"Financing Lease Payment From Unconsolidated Affiliate" },
                         { :klass=>:d, :item_string=>"Increase Decrease In Restricted Cash" },
                         { :klass=>:i, :item_string=>"Payments For Proceeds From Other Investing Activities" },
                         { :klass=>:d, :item_string=>"Borrowings Under Revolving Credit Facilities" },
                         { :klass=>:d, :item_string=>"Payments Under Revolving Credit Facilities" },
                         { :klass=>:d, :item_string=>"Proceeds From Lines Of Credit" },
                         { :klass=>:d, :item_string=>"Repayments Of Lines Of Credit" },
                         { :klass=>:d, :item_string=>"Proceeds From Issuance Of Other Long Term Debt" },
                         { :klass=>:d, :item_string=>"Proceeds From Related Party Debt" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt" },
                         { :klass=>:d, :item_string=>"Payments Of Debt Issuance Costs" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:f, :item_string=>"Proceeds From Issuance Of Shares Under Incentive And Share Based Compensation Plans Including Stock Options" },
                         { :klass=>:f, :item_string=>"Payments Related To Tax Withholding For Share Based Compensation" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents" },

                         { :klass=>:c, :item_string=>"Net Income Loss" },
                         { :klass=>:c, :item_string=>"Depreciation And Amortization" },
                         { :klass=>:c, :item_string=>"Deferred Income Tax Expense Benefit" },
                         { :klass=>:c, :item_string=>"Provision For Doubtful Accounts" },
                         { :klass=>:c, :item_string=>"Share Based Compensation" },
                         { :klass=>:c, :item_string=>"Excess Tax Benefit From Share Based Compensation Operating Activities" },
                         { :klass=>:c, :item_string=>"Other Noncash Income Expense" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Receivable" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Prepaid Deferred Expense And Other Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Assets" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accounts Payable And Accrued Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Deferred Revenue" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Other Operating Liabilities" },
                         { :klass=>:c, :item_string=>"Increase Decrease In Accrued Income Taxes Payable" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Productive Assets" },
                         { :klass=>:d, :item_string=>"Payments To Acquire Short Term Investments" },
                         { :klass=>:d, :item_string=>"Proceeds From Sale Of Short Term Investments" },
                         { :klass=>:i, :item_string=>"Payments To Acquire Businesses Net Of Cash Acquired" },
                         { :klass=>:d, :item_string=>"Repayments Of Long Term Debt" },
                         { :klass=>:i, :item_string=>"Repayments Of Long Term Capital Lease Obligations" },
                         { :klass=>:f, :item_string=>"Payments For Repurchase Of Common Stock" },
                         { :klass=>:f, :item_string=>"Proceeds From Issuance Of Shares Under Incentive And Share Based Compensation Plans" },
                         { :klass=>:f, :item_string=>"Proceeds From Stock Options Exercised" },
                         { :klass=>:f, :item_string=>"Excess Tax Benefit From Share Based Compensation Financing Activities" },
                         { :klass=>:d, :item_string=>"Effect Of Exchange Rate On Cash And Cash Equivalents" } ]
  end
end
